---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: pfe-cicd
description: pfe-cicd
serialPipeline:
  stages:
  - targetId: dev
  - targetId: prod
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: Dev Environment
run:
  location: projects/${PROJECT_ID}/locations/asia-northeast1
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: Production Environment
run:
  location: projects/${PROJECT_ID}/locations/asia-northeast2
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: pfe-cicd/promote
description: promotes a release
suspended: false
serviceAccount: ${PROJECT_NUMBER}-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: dev
rules:
- promoteReleaseRule:
    name: "promote-release"
    wait: 1m
    toTargetId: "@next"

